# Generated by Django 4.2.5 on 2023-10-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('concept', models.CharField(default='TBD', max_length=30, verbose_name='Concept')),
                ('rules_system', models.CharField(default='TBD', max_length=10, verbose_name='System')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
            ],
        ),
    ]
