# Generated by Django 4.2.5 on 2023-10-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('concept', models.CharField(default='TBD', max_length=30, verbose_name='Concept')),
                ('rules_system', models.CharField(default='TBD', max_length=10, null=True, verbose_name='System')),
                ('growth', models.IntegerField(default=0, verbose_name='Current level or Exp')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('creator', models.CharField(default='Zalo', max_length=15, verbose_name="Creator's name")),
                ('is_player', models.BooleanField(default=True, verbose_name="Is a player's character?")),
                ('alive', models.BooleanField(default=True, verbose_name='Is alive?')),
                ('bio', models.CharField(max_length=300, null=True, verbose_name='Biography')),
                ('portrait', models.URLField(null=True, verbose_name="Portraits' URL")),
            ],
        ),
    ]
