# Generated by Django 4.2.5 on 2023-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulessystem',
            name='edition',
            field=models.IntegerField(default=1, null=True, verbose_name='Version or Edition'),
        ),
        migrations.AlterField(
            model_name='rulessystem',
            name='system_name',
            field=models.CharField(max_length=20, null=True, verbose_name='System'),
        ),
    ]
