# Generated by Django 4.2.5 on 2023-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rulessystem_edition_alter_rulessystem_system_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Name'),
        ),
    ]
